In [1]:
import torch

/home/nayakab/Desktop/python-virtual-env/env/lib/python3.6/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}


In [37]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 1.4504,  0.1775, -0.4907], requires_grad=True)


In [38]:
y = x ** 2
y.retain_grad()
y

tensor([2.1036, 0.0315, 0.2408], grad_fn=<PowBackward0>)

In [39]:
z = y ** 2 + 2 
z

tensor([6.4252, 2.0010, 2.0580], grad_fn=<AddBackward0>)

In [40]:
# Jacobian Vector product - specify the vector or use a scalar
#z.sum().backward()
vector_v = torch.Tensor(3)
z.backward(vector_v)

In [41]:
x.grad

tensor([-2.4805e+13,  1.0258e-42, -2.3197e-36])

In [42]:
y.grad

tensor([-8.5512e+12,  2.8881e-42,  2.3635e-36])

In [44]:
# Blocking gradients
x.requires_grad_(False)
x.detach()
x.requires_grad_(True)
with torch.no_grad():
    # No gradient for y because no gradient for x
    y = x ** 2
    print(y)    

tensor([2.1036, 0.0315, 0.2408])


In [46]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
    output = weights * 3 
    output = output.sum()
    
    output.backward()
    
    print(weights.grad)
    
    # Make Grad zero everytime because Torch keeps accumulating these gradients  
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


### Backpropagation

In [49]:
# Computational Graph is created with each calculation
import torch 
x = torch.tensor(1.0)
y = torch.tensor(2.0)

weights = torch.tensor(1.0, requires_grad=True)

# Forward
y_ = weights * x
loss = (y_ - y) ** 2
print(loss)

loss.backward() 
print(weights.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
